package ph.edu.dlsu.mobdeve.s14.cervales.shams.parehome.model

data class Listing(
    var firstName: String,
    var lastName: String,
    var phoneNumber: String,
    var emailAddress: String,
    var name: String,
    var roomNumber: String,
    var totalOccupancy: String,
    var totalBedrooms: String,
    var totalBathrooms: String,
    var description: String,

    var addressExactAddress: String,
    var addressCountry: String,
    var addressRegion: String,
    var addressCity: String,
    var addressPostalCode: String,
    var addressStreet: String,

    var price: String,
    var ownerId: String,
    var picture1: String,
    var picture2: String,
    var picture3: String,
    var picture4: String,
    var picture5: String,

    var longitude: String,
    var latitude: String,
) {
    constructor() : this("",
                "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ) {}

}